spring:
  datasource:
    username: root
    password: wang2002
    url: jdbc:mysql://localhost:3306/db_stack?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8000
